# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BusinessRegistrationTypeEnum(str, Enum):
    """
    The type of business registration number.
    """

    """
    allowed enum values
    """
    EIN = 'EIN'
    CBN = 'CBN'
    NEQ = 'NEQ'
    PROVINCIAL_NUMBER = 'PROVINCIAL_NUMBER'
    CRN = 'CRN'
    VAT = 'VAT'
    ACN = 'ACN'
    ABN = 'ABN'
    BRN = 'BRN'
    SIREN = 'SIREN'
    SIRET = 'SIRET'
    NZBN = 'NZBN'
    UST_IDNR = 'UST_IDNR'
    CIF = 'CIF'
    NIF = 'NIF'
    CNPJ = 'CNPJ'
    UID = 'UID'
    OTHER = 'OTHER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BusinessRegistrationTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


