# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BusinessRegistrationTypeEnum(str, Enum):
    """
    The type of business registration number. Optional until early 2026; required if `businessRegistrationNumber` is provided. Available starting October 1st, 2025.
    """

    """
    allowed enum values
    """
    EIN = 'EIN'
    CBN = 'CBN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BusinessRegistrationTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


