# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ConferenceStateEnum(str, Enum):
    """
    Setting the conference state to `completed` ends the conference and ejects all members.
    """

    """
    allowed enum values
    """
    ACTIVE = 'active'
    COMPLETED = 'completed'

    @classmethod
    def from_json(cls, json_str: str) -> ConferenceStateEnum:
        """Create an instance of ConferenceStateEnum from a JSON string"""
        return ConferenceStateEnum(json.loads(json_str))


