# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InboundCallbackTypeEnum(str, Enum):
    """
    The possible inbound callback types originating from MO messages or multichannel message client responses: - `message-received` indicates an MO message from a Bandwidth user's client to a Bandwidth number. - `request-location-response` indicates a response to a location request sent by the Bandwidth user's client after receiving an RBM message.  - `suggestion-response` indicates a response to a suggestion sent by the Bandwidth user's client after receiving an RBM message.
    """

    """
    allowed enum values
    """
    MESSAGE_MINUS_RECEIVED = 'message-received'
    REQUEST_MINUS_LOCATION_MINUS_RESPONSE = 'request-location-response'
    SUGGESTION_MINUS_RESPONSE = 'suggestion-response'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InboundCallbackTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


