# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MessageTypeEnum(str, Enum):
    """
    The type of message. Either SMS or MMS.
    """

    """
    allowed enum values
    """
    SMS = 'sms'
    MMS = 'mms'

    @classmethod
    def from_json(cls, json_str: str) -> MessageTypeEnum:
        """Create an instance of MessageTypeEnum from a JSON string"""
        return MessageTypeEnum(json.loads(json_str))


