# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class A2pStateEnum(object):

    """Implementation of the 'A2pState' enum.

    TODO: type enum description here.

    Attributes:
        OFF: TODO: type description here.
        SYSTEM_DEFAULT: TODO: type description here.
        OVERRIDDEN: TODO: type description here.

    """

    OFF = 'OFF'

    SYSTEM_DEFAULT = 'SYSTEM_DEFAULT'

    OVERRIDDEN = 'OVERRIDDEN'
