# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ActionEnum(object):

    """Implementation of the 'Action' enum.

    TODO: type enum description here.

    Attributes:
        UNCHANGED: TODO: type description here.
        OFF: TODO: type description here.
        AS_SPECIFIED: TODO: type description here.
        INCORRECT_VALUE: TODO: type description here.

    """

    UNCHANGED = 'UNCHANGED'

    OFF = 'OFF'

    AS_SPECIFIED = 'AS_SPECIFIED'

    INCORRECT_VALUE = 'INCORRECT_VALUE'
