# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ConnectionTypeEnum(object):

    """Implementation of the 'ConnectionType' enum.

    TODO: type enum description here.

    Attributes:
        TRANSCEIVER: TODO: type description here.
        SENDER_ONLY: TODO: type description here.
        RECEIVER_ONLY: TODO: type description here.

    """

    TRANSCEIVER = 'TRANSCEIVER'

    SENDER_ONLY = 'SENDER_ONLY'

    RECEIVER_ONLY = 'RECEIVER_ONLY'
