# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class DeckTypeEnum(object):

    """Implementation of the 'DeckType' enum.

    TODO: type enum description here.

    Attributes:
        NPANXX: TODO: type description here.
        LATAOCN: TODO: type description here.

    """

    NPANXX = 'NPANXX'

    LATAOCN = 'LATAOCN'
