# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class EndpointTypeEnum(object):

    """Implementation of the 'EndpointType' enum.

    TODO: type enum description here.

    Attributes:
        TN: TODO: type description here.
        IPV4: TODO: type description here.
        SIP: TODO: type description here.
        FQDN: TODO: type description here.

    """

    TN = 'TN'

    IPV4 = 'IPv4'

    SIP = 'SIP'

    FQDN = 'FQDN'
