# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class EnrNotificationTypeEnum(object):

    """Implementation of the 'EnrNotificationType' enum.

    TODO: type enum description here.

    Attributes:
        EMAIL: TODO: type description here.
        SMS: TODO: type description here.
        TTS: TODO: type description here.
        CALLBACK: TODO: type description here.
        UNRECOGNIZED_TYPE: TODO: type description here.

    """

    EMAIL = 'EMAIL'

    SMS = 'SMS'

    TTS = 'TTS'

    CALLBACK = 'CALLBACK'

    UNRECOGNIZED_TYPE = 'UNRECOGNIZED_TYPE'
