# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class OrderStatus1Enum(object):

    """Implementation of the 'OrderStatus1' enum.

    TODO: type enum description here.

    Attributes:
        FOC: TODO: type description here.
        EXCEPTION: TODO: type description here.
        PENDING: TODO: type description here.
        COMPLETE: TODO: type description here.
        CANCELLED: TODO: type description here.
        FAILED: TODO: type description here.
        PARTIAL: TODO: type description here.

    """

    FOC = 'FOC'

    EXCEPTION = 'EXCEPTION'

    PENDING = 'PENDING'

    COMPLETE = 'COMPLETE'

    CANCELLED = 'CANCELLED'

    FAILED = 'FAILED'

    PARTIAL = 'PARTIAL'
