# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class OrderTypeEnum(object):

    """Implementation of the 'OrderType' enum.

    TODO: type enum description here.

    Attributes:
        BULK_PORT_IN: TODO: type description here.
        PORT_IN: TODO: type description here.
        PORT_OUT: TODO: type description here.
        NEW_NUMBER: TODO: type description here.
        DISCONNECT: TODO: type description here.
        IMPORT_TO_ACCOUNT: TODO: type description here.
        LIDB: TODO: type description here.
        DLDA: TODO: type description here.
        LSR: TODO: type description here.
        E911: TODO: type description here.
        TN_OPTION: TODO: type description here.
        EXTERNAL_TNS: TODO: type description here.
        NUMBERS_ASSIGNMENT: TODO: type description here.
        IMPORT_TN_ORDERS: TODO: type description here.
        REMOVE_IMPORTED_TN_ORDERS: TODO: type description here.
        CSR: TODO: type description here.
        EMERGENCY_NOTIFICATION_GROUP: TODO: type description here.
        EMERGENCY_ENDPOINT_GROUP: TODO: type description here.

    """

    BULK_PORT_IN = 'bulk_port_in'

    PORT_IN = 'port_in'

    PORT_OUT = 'port_out'

    NEW_NUMBER = 'new_number'

    DISCONNECT = 'disconnect'

    IMPORT_TO_ACCOUNT = 'import_to_account'

    LIDB = 'lidb'

    DLDA = 'dlda'

    LSR = 'lsr'

    E911 = 'e911'

    TN_OPTION = 'tn_option'

    EXTERNAL_TNS = 'external_tns'

    NUMBERS_ASSIGNMENT = 'numbers_assignment'

    IMPORT_TN_ORDERS = 'import_tn_orders'

    REMOVE_IMPORTED_TN_ORDERS = 'remove_imported_tn_orders'

    CSR = 'csr'

    EMERGENCY_NOTIFICATION_GROUP = 'emergency_notification_group'

    EMERGENCY_ENDPOINT_GROUP = 'emergency_endpoint_group'
