# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class PortOutStatusEnum(object):

    """Implementation of the 'PortOutStatus' enum.

    TODO: type enum description here.

    Attributes:
        NEW: TODO: type description here.
        SUPP: TODO: type description here.
        MODIFY: TODO: type description here.
        COMPLETE: TODO: type description here.
        CANCELLED: TODO: type description here.
        VALIDATION_FAILED_NEW: TODO: type description here.
        VALIDATION_FAILED_SUPP: TODO: type description here.
        VALIDATION_FAILED_MODIFY: TODO: type description here.
        EXCEPTION: TODO: type description here.
        SOA_PENDING: TODO: type description here.
        SOA_CONFLICT: TODO: type description here.

    """

    NEW = 'NEW'

    SUPP = 'SUPP'

    MODIFY = 'MODIFY'

    COMPLETE = 'COMPLETE'

    CANCELLED = 'CANCELLED'

    VALIDATION_FAILED_NEW = 'VALIDATION_FAILED_NEW'

    VALIDATION_FAILED_SUPP = 'VALIDATION_FAILED_SUPP'

    VALIDATION_FAILED_MODIFY = 'VALIDATION_FAILED_MODIFY'

    EXCEPTION = 'EXCEPTION'

    SOA_PENDING = 'SOA_PENDING'

    SOA_CONFLICT = 'SOA_CONFLICT'
