# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class PortInTypeEnum(object):

    """Implementation of the 'PortInType' enum.

    TODO: type enum description here.

    Attributes:
        INTERNAL: TODO: type description here.
        AUTOMATED: TODO: type description here.
        AUTOMATEDOFFNET: TODO: type description here.
        MANUALOFFNET: TODO: type description here.
        MANUAL_TOLLFREE: TODO: type description here.
        MIXED: TODO: type description here.
        MANUAL_ON_NET: TODO: type description here.

    """

    INTERNAL = 'INTERNAL'

    AUTOMATED = 'AUTOMATED'

    AUTOMATEDOFFNET = 'AUTOMATEDOFFNET'

    MANUALOFFNET = 'MANUALOFFNET'

    MANUAL_TOLLFREE = 'MANUAL_TOLLFREE'

    MIXED = 'MIXED'

    MANUAL_ON_NET = 'MANUAL_ON_NET'
