# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class PreferredLanguageEnum(object):

    """Implementation of the 'PreferredLanguage' enum.

    TODO: type enum description here.

    Attributes:
        EN: TODO: type description here.
        FR: TODO: type description here.
        ENUM_INCORRECT VALUE: TODO: type description here.

    """

    EN = 'en'

    FR = 'fr'

    ENUM_INCORRECT_VALUE = 'Incorrect value'
