# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class SubscriberTypeEnum(object):

    """Implementation of the 'SubscriberType' enum.

    TODO: type enum description here.

    Attributes:
        BUSINESS: TODO: type description here.
        RESIDENTIAL: TODO: type description here.

    """

    BUSINESS = 'BUSINESS'

    RESIDENTIAL = 'RESIDENTIAL'
