# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from bandwidth.utilities.xml_utilities import XmlUtilities


class TerminationRoutingExceptionFile(object):

    """Implementation of the 'TerminationRoutingExceptionFile' model.

    TODO: type model description here.

    Attributes:
        id (long|int): TODO: type description here.
        routing_exception_name (string): TODO: type description here.
        file_name (string): TODO: type description here.
        file_bytes (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "routing_exception_name": 'routingExceptionName',
        "file_name": 'fileName',
        "file_bytes": 'fileBytes'
    }

    def __init__(self,
                 id=None,
                 routing_exception_name=None,
                 file_name=None,
                 file_bytes=None):
        """Constructor for the TerminationRoutingExceptionFile class"""

        # Initialize members of the class
        self.id = id
        self.routing_exception_name = routing_exception_name
        self.file_name = file_name
        self.file_bytes = file_bytes

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        routing_exception_name = dictionary.get('routingExceptionName')
        file_name = dictionary.get('fileName')
        file_bytes = dictionary.get('fileBytes')

        # Return an object of this model
        return cls(id,
                   routing_exception_name,
                   file_name,
                   file_bytes)

    @classmethod
    def from_element(cls, root):
        """Initialize an instance of this class using an xml.etree.Element.

        Args:
            root (string): The root xml element.

        Returns:
            object: An instance of this class.

        """
        id = XmlUtilities.value_from_xml_element(root.find('id'), int)
        routing_exception_name = XmlUtilities.value_from_xml_element(root.find('routingExceptionName'), str)
        file_name = XmlUtilities.value_from_xml_element(root.find('fileName'), str)
        file_bytes = XmlUtilities.list_from_xml_element(root, 'fileBytes', str)

        return cls(id,
                   routing_exception_name,
                   file_name,
                   file_bytes)

    def to_xml_sub_element(self, root):
        """Convert this object to an instance of xml.etree.Element.

        Args:
            root (xml.etree.Element): The parent of this xml element.
        """
        XmlUtilities.add_as_subelement(root, self.id, 'id')
        XmlUtilities.add_as_subelement(root, self.routing_exception_name, 'routingExceptionName')
        XmlUtilities.add_as_subelement(root, self.file_name, 'fileName')
        XmlUtilities.add_list_as_subelement(root, self.file_bytes, 'fileBytes')
