# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from bandwidth.utilities.xml_utilities import XmlUtilities


class TerminationRateDeck(object):

    """Implementation of the 'TerminationRateDeck' model.

    TODO: type model description here.

    Attributes:
        deck_byte_buffer (list of string): TODO: type description here.
        deck_file_type (DeckFileTypeEnum): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "deck_byte_buffer": 'deckByteBuffer',
        "deck_file_type": 'deckFileType'
    }

    def __init__(self,
                 deck_byte_buffer=None,
                 deck_file_type=None):
        """Constructor for the TerminationRateDeck class"""

        # Initialize members of the class
        self.deck_byte_buffer = deck_byte_buffer
        self.deck_file_type = deck_file_type

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        deck_byte_buffer = dictionary.get('deckByteBuffer')
        deck_file_type = dictionary.get('deckFileType')

        # Return an object of this model
        return cls(deck_byte_buffer,
                   deck_file_type)

    @classmethod
    def from_element(cls, root):
        """Initialize an instance of this class using an xml.etree.Element.

        Args:
            root (string): The root xml element.

        Returns:
            object: An instance of this class.

        """
        deck_byte_buffer = XmlUtilities.list_from_xml_element(root, 'deckByteBuffer', str)
        deck_file_type = XmlUtilities.value_from_xml_element(root.find('deckFileType'), str)

        return cls(deck_byte_buffer,
                   deck_file_type)

    def to_xml_sub_element(self, root):
        """Convert this object to an instance of xml.etree.Element.

        Args:
            root (xml.etree.Element): The parent of this xml element.
        """
        XmlUtilities.add_list_as_subelement(root, self.deck_byte_buffer, 'deckByteBuffer')
        XmlUtilities.add_as_subelement(root, self.deck_file_type, 'deckFileType')
