# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from bandwidth.iris.models.tn_option_group import TnOptionGroup
from bandwidth.iris.models.tn_option_order_error import TnOptionOrderError
from bandwidth.iris.models.tn_option_order_warning_payload import TnOptionOrderWarningPayload
from bandwidth.utilities.xml_utilities import XmlUtilities


class TnOptionOrderPayload(object):

    """Implementation of the 'TnOptionOrderPayload' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        account_id (int): TODO: type description here.
        name (string): TODO: type description here.
        last_modified_date_in_utc (string): TODO: type description here.
        last_modified_by (string): TODO: type description here.
        created_by_user (string): TODO: type description here.
        customer_order_id (string): TODO: type description here.
        site_id (int): TODO: type description here.
        peer_id (int): TODO: type description here.
        order_create_date (string): TODO: type description here.
        processing_status (ProcessingStatus5Enum): TODO: type description
            here.
        tn_option_groups (list of TnOptionGroup): TODO: type description
            here.
        errors (list of TnOptionOrderError): TODO: type description here.
        warnings (list of TnOptionOrderWarningPayload): TODO: type description
            here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "account_id": 'accountId',
        "name": 'name',
        "last_modified_date_in_utc": 'lastModifiedDateInUtc',
        "last_modified_by": 'lastModifiedBy',
        "created_by_user": 'createdByUser',
        "customer_order_id": 'customerOrderId',
        "site_id": 'siteId',
        "peer_id": 'peerId',
        "order_create_date": 'orderCreateDate',
        "processing_status": 'processingStatus',
        "tn_option_groups": 'tnOptionGroups',
        "errors": 'errors',
        "warnings": 'warnings'
    }

    def __init__(self,
                 id=None,
                 account_id=None,
                 name=None,
                 last_modified_date_in_utc=None,
                 last_modified_by=None,
                 created_by_user=None,
                 customer_order_id=None,
                 site_id=None,
                 peer_id=None,
                 order_create_date=None,
                 processing_status=None,
                 tn_option_groups=None,
                 errors=None,
                 warnings=None):
        """Constructor for the TnOptionOrderPayload class"""

        # Initialize members of the class
        self.id = id
        self.account_id = account_id
        self.name = name
        self.last_modified_date_in_utc = last_modified_date_in_utc
        self.last_modified_by = last_modified_by
        self.created_by_user = created_by_user
        self.customer_order_id = customer_order_id
        self.site_id = site_id
        self.peer_id = peer_id
        self.order_create_date = order_create_date
        self.processing_status = processing_status
        self.tn_option_groups = tn_option_groups
        self.errors = errors
        self.warnings = warnings

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        account_id = dictionary.get('accountId')
        name = dictionary.get('name')
        last_modified_date_in_utc = dictionary.get('lastModifiedDateInUtc')
        last_modified_by = dictionary.get('lastModifiedBy')
        created_by_user = dictionary.get('createdByUser')
        customer_order_id = dictionary.get('customerOrderId')
        site_id = dictionary.get('siteId')
        peer_id = dictionary.get('peerId')
        order_create_date = dictionary.get('orderCreateDate')
        processing_status = dictionary.get('processingStatus')
        tn_option_groups = None
        if dictionary.get('tnOptionGroups') is not None:
            tn_option_groups = [TnOptionGroup.from_dictionary(x) for x in dictionary.get('tnOptionGroups')]
        errors = None
        if dictionary.get('errors') is not None:
            errors = [TnOptionOrderError.from_dictionary(x) for x in dictionary.get('errors')]
        warnings = None
        if dictionary.get('warnings') is not None:
            warnings = [TnOptionOrderWarningPayload.from_dictionary(x) for x in dictionary.get('warnings')]

        # Return an object of this model
        return cls(id,
                   account_id,
                   name,
                   last_modified_date_in_utc,
                   last_modified_by,
                   created_by_user,
                   customer_order_id,
                   site_id,
                   peer_id,
                   order_create_date,
                   processing_status,
                   tn_option_groups,
                   errors,
                   warnings)

    @classmethod
    def from_element(cls, root):
        """Initialize an instance of this class using an xml.etree.Element.

        Args:
            root (string): The root xml element.

        Returns:
            object: An instance of this class.

        """
        id = XmlUtilities.value_from_xml_element(root.find('OrderId'), str)
        account_id = XmlUtilities.value_from_xml_element(root.find('AccountId'), int)
        name = XmlUtilities.value_from_xml_element(root.find('Name'), str)
        last_modified_date_in_utc = XmlUtilities.value_from_xml_element(root.find('LastModifiedDate'), str)
        last_modified_by = XmlUtilities.value_from_xml_element(root.find('LastModifiedBy'), str)
        created_by_user = XmlUtilities.value_from_xml_element(root.find('CreatedByUser'), str)
        customer_order_id = XmlUtilities.value_from_xml_element(root.find('CustomerOrderId'), str)
        site_id = XmlUtilities.value_from_xml_element(root.find('SiteId'), int)
        peer_id = XmlUtilities.value_from_xml_element(root.find('PeerId'), int)
        order_create_date = XmlUtilities.value_from_xml_element(root.find('OrderCreateDate'), str)
        processing_status = XmlUtilities.value_from_xml_element(root.find('ProcessingStatus'), str)
        tn_option_groups = XmlUtilities.list_from_xml_element(
            root, 'TnOptionGroup', TnOptionGroup, wrapping_element_name='TnOptionGroups')
        errors = XmlUtilities.list_from_xml_element(
            root, 'Error', TnOptionOrderError, wrapping_element_name='ErrorList')
        warnings = XmlUtilities.list_from_xml_element(
            root, 'Warning', TnOptionOrderWarningPayload, wrapping_element_name='Warnings')

        return cls(id,
                   account_id,
                   name,
                   last_modified_date_in_utc,
                   last_modified_by,
                   created_by_user,
                   customer_order_id,
                   site_id,
                   peer_id,
                   order_create_date,
                   processing_status,
                   tn_option_groups,
                   errors,
                   warnings)

    def to_xml_sub_element(self, root):
        """Convert this object to an instance of xml.etree.Element.

        Args:
            root (xml.etree.Element): The parent of this xml element.
        """
        XmlUtilities.add_as_subelement(root, self.id, 'OrderId')
        XmlUtilities.add_as_subelement(root, self.account_id, 'AccountId')
        XmlUtilities.add_as_subelement(root, self.name, 'Name')
        XmlUtilities.add_as_subelement(root, self.last_modified_date_in_utc, 'LastModifiedDate')
        XmlUtilities.add_as_subelement(root, self.last_modified_by, 'LastModifiedBy')
        XmlUtilities.add_as_subelement(root, self.created_by_user, 'CreatedByUser')
        XmlUtilities.add_as_subelement(root, self.customer_order_id, 'CustomerOrderId')
        XmlUtilities.add_as_subelement(root, self.site_id, 'SiteId')
        XmlUtilities.add_as_subelement(root, self.peer_id, 'PeerId')
        XmlUtilities.add_as_subelement(root, self.order_create_date, 'OrderCreateDate')
        XmlUtilities.add_as_subelement(root, self.processing_status, 'ProcessingStatus')
        XmlUtilities.add_list_as_subelement(root, self.tn_option_groups, 'TnOptionGroup',
                                            wrapping_element_name='TnOptionGroups')
        XmlUtilities.add_list_as_subelement(root, self.errors, 'Error',
                                            wrapping_element_name='ErrorList')
        XmlUtilities.add_list_as_subelement(root, self.warnings, 'Warning',
                                            wrapping_element_name='Warnings')
