# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ValidationTypeEnum(object):

    """Implementation of the 'ValidationType' enum.

    TODO: type enum description here.

    Attributes:
        REGEX: TODO: type description here.
        LIST: TODO: type description here.
        MASK: TODO: type description here.
        GENERIC: TODO: type description here.

    """

    REGEX = 'REGEX'

    LIST = 'LIST'

    MASK = 'MASK'

    GENERIC = 'GENERIC'
