"""
    Messaging

    Test Bandwidth's HTTP Messaging platform ## Base Path <code>https://messaging.bandwidth.com/api/v2</code>  # noqa: E501

    The version of the OpenAPI document: 4.2.8
    Generated by: https://openapi-generator.tech
"""


import unittest

import bandwidth
from bandwidth.api.calls_api import CallsApi  # noqa: E501


class TestCallsApi(unittest.TestCase):
    """CallsApi unit test stubs"""

    def setUp(self):
        self.api = CallsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_call(self):
        """Test case for create_call

        Create Call  # noqa: E501
        """
        pass

    def test_get_call(self):
        """Test case for get_call

        Get Call Information  # noqa: E501
        """
        pass

    def test_modify_call(self):
        """Test case for modify_call

        Modify Call  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
