"""
    Bandwidth

    Bandwidth's Communication APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.two_factor_verify_code_response import TwoFactorVerifyCodeResponse


class TestTwoFactorVerifyCodeResponse(unittest.TestCase):
    """TwoFactorVerifyCodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwoFactorVerifyCodeResponse(self):
        """Test TwoFactorVerifyCodeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TwoFactorVerifyCodeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
