"""
    Messaging

    Bandwidth's HTTP Messaging platform ## Base Path <code>https://messaging.bandwidth.com/api/v2</code>  # noqa: E501

    The version of the OpenAPI document: 4.2.8
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.unauthorized_request import UnauthorizedRequest


class TestUnauthorizedRequest(unittest.TestCase):
    """UnauthorizedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnauthorizedRequest(self):
        """Test UnauthorizedRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnauthorizedRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
