"""
    Messaging

    This is a demo  # noqa: E501

    The version of the OpenAPI document: 4.2.8
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.transcribe_recording_request import TranscribeRecordingRequest


class TestTranscribeRecordingRequest(unittest.TestCase):
    """TranscribeRecordingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscribeRecordingRequest(self):
        """Test TranscribeRecordingRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TranscribeRecordingRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
