"""
    Bandwidth

    Bandwidth's Communication APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.call_state import CallState


class TestCallState(unittest.TestCase):
    """CallState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCallState(self):
        """Test CallState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CallState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
