"""
    Messaging

    This is a demo  # noqa: E501

    The version of the OpenAPI document: 4.2.8
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.two_factor_voice_response import TwoFactorVoiceResponse


class TestTwoFactorVoiceResponse(unittest.TestCase):
    """TwoFactorVoiceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwoFactorVoiceResponse(self):
        """Test TwoFactorVoiceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TwoFactorVoiceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
