"""
    Messaging

    This is a demo  # noqa: E501

    The version of the OpenAPI document: 4.2.8
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.message_request import MessageRequest


class TestMessageRequest(unittest.TestCase):
    """MessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageRequest(self):
        """Test MessageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
