"""
    Bandwidth

    Bandwidth's Communication APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.callback_method_enum import CallbackMethodEnum
from bandwidth.model.machine_detection_configuration import MachineDetectionConfiguration
globals()['CallbackMethodEnum'] = CallbackMethodEnum
globals()['MachineDetectionConfiguration'] = MachineDetectionConfiguration
from bandwidth.model.create_call import CreateCall


class TestCreateCall(unittest.TestCase):
    """CreateCall unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCall(self):
        """Test CreateCall"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateCall()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
