"""
    Messaging

    Test Bandwidth's HTTP Messaging platform ## Base Path <code>https://messaging.bandwidth.com/api/v2</code>  # noqa: E501

    The version of the OpenAPI document: 4.2.8
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.order_status_result import OrderStatusResult
globals()['OrderStatusResult'] = OrderStatusResult
from bandwidth.model.order_status import OrderStatus


class TestOrderStatus(unittest.TestCase):
    """OrderStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderStatus(self):
        """Test OrderStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
