"""
    Bandwidth

    Bandwidth's Communication APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.modify_call_recording_request import ModifyCallRecordingRequest


class TestModifyCallRecordingRequest(unittest.TestCase):
    """ModifyCallRecordingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyCallRecordingRequest(self):
        """Test ModifyCallRecordingRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifyCallRecordingRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
