"""
    Messaging

    Bandwidth's HTTP Messaging platform ## Base Path <code>https://messaging.bandwidth.com/api/v2</code>  # noqa: E501

    The version of the OpenAPI document: 4.2.8
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.two_factor_code_request_schema import TwoFactorCodeRequestSchema


class TestTwoFactorCodeRequestSchema(unittest.TestCase):
    """TwoFactorCodeRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwoFactorCodeRequestSchema(self):
        """Test TwoFactorCodeRequestSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TwoFactorCodeRequestSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
