"""
    Bandwidth

    Bandwidth's Communication APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.api_error import ApiError


class TestApiError(unittest.TestCase):
    """ApiError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiError(self):
        """Test ApiError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
