"""
    Bandwidth

    Bandwidth's Communication APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.order_status_result import OrderStatusResult
globals()['OrderStatusResult'] = OrderStatusResult
from bandwidth.model.order_status import OrderStatus


class TestOrderStatus(unittest.TestCase):
    """OrderStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderStatus(self):
        """Test OrderStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
