"""
    Bandwidth

    Bandwidth's Communication APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bandwidth
from bandwidth.model.redirect_method_enum import RedirectMethodEnum


class TestRedirectMethodEnum(unittest.TestCase):
    """RedirectMethodEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedirectMethodEnum(self):
        """Test RedirectMethodEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedirectMethodEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
