# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.rbm_veb_view_enum import RbmVebViewEnum

class TestRbmVebViewEnum(unittest.TestCase):
    """RbmVebViewEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRbmVebViewEnum(self):
        """Test RbmVebViewEnum"""
        assert RbmVebViewEnum('FULL') == 'FULL'
        assert RbmVebViewEnum('HALF') == 'HALF'
        assert RbmVebViewEnum('TALL') == 'TALL'

if __name__ == '__main__':
    unittest.main()
