# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.device_status_enum import DeviceStatusEnum

class TestDeviceStatusEnum(unittest.TestCase):
    """DeviceStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceStatusEnum(self):
        """Test DeviceStatusEnum"""
        assert DeviceStatusEnum('CONNECTED') == 'CONNECTED'
        assert DeviceStatusEnum('DISCONNECTED') == 'DISCONNECTED'

if __name__ == '__main__':
    unittest.main()
