# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.mfa_request_error import MfaRequestError

class TestMfaRequestError(unittest.TestCase):
    """MfaRequestError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MfaRequestError:
        """Test MfaRequestError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return MfaRequestError(
                error = '400 Request is malformed or invalid',
                request_id = '354cc8a3-6701-461e-8fa7-8671703dd898'
            )
        else:
            return MfaRequestError(
        )

    def testMfaRequestError(self):
        """Test MfaRequestError"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, MfaRequestError)
        assert instance.error == '400 Request is malformed or invalid'
        assert instance.request_id == '354cc8a3-6701-461e-8fa7-8671703dd898'

if __name__ == '__main__':
    unittest.main()
