# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from uuid import UUID

from bandwidth.models.create_async_bulk_lookup_response_data import CreateAsyncBulkLookupResponseData
from bandwidth.models.in_progress_lookup_status_enum import InProgressLookupStatusEnum

class TestCreateAsyncBulkLookupResponseData(unittest.TestCase):
    """CreateAsyncBulkLookupResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAsyncBulkLookupResponseData:
        """Test CreateAsyncBulkLookupResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return CreateAsyncBulkLookupResponseData(
                request_id = UUID('004223a0-8b17-41b1-bf81-20732adf5590'),
                status = InProgressLookupStatusEnum('COMPLETE')
            )
        else:
            return CreateAsyncBulkLookupResponseData(
        )

    def testCreateAsyncBulkLookupResponseData(self):
        """Test CreateAsyncBulkLookupResponseData"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, CreateAsyncBulkLookupResponseData)
        assert instance.request_id == UUID('004223a0-8b17-41b1-bf81-20732adf5590')
        assert instance.status == InProgressLookupStatusEnum('COMPLETE')

if __name__ == '__main__':
    unittest.main()
