# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.business_registration_issuing_country_enum import BusinessRegistrationIssuingCountryEnum

class TestBusinessRegistrationIssuingCountryEnum(unittest.TestCase):
    """BusinessRegistrationIssuingCountryEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBusinessRegistrationIssuingCountryEnum(self):
        """Test BusinessRegistrationIssuingCountryEnum"""
        assert BusinessRegistrationIssuingCountryEnum('USA') == 'USA'
        assert BusinessRegistrationIssuingCountryEnum('CAN') == 'CAN'
        assert BusinessRegistrationIssuingCountryEnum('HKG') == 'HKG'
        assert BusinessRegistrationIssuingCountryEnum('GBR') == 'GBR'
        assert BusinessRegistrationIssuingCountryEnum('IRL') == 'IRL'
        assert BusinessRegistrationIssuingCountryEnum('BRA') == 'BRA'
        assert BusinessRegistrationIssuingCountryEnum('NLD') == 'NLD'
        assert BusinessRegistrationIssuingCountryEnum('AUS') == 'AUS'
        assert BusinessRegistrationIssuingCountryEnum('FRA') == 'FRA'
        assert BusinessRegistrationIssuingCountryEnum('NZL') == 'NZL'
        assert BusinessRegistrationIssuingCountryEnum('DEU') == 'DEU'
        assert BusinessRegistrationIssuingCountryEnum('ESP') == 'ESP'
        assert BusinessRegistrationIssuingCountryEnum('CHE') == 'CHE'


if __name__ == '__main__':
    unittest.main()
