# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.create_lookup_response import CreateLookupResponse

class TestCreateLookupResponse(unittest.TestCase):
    """CreateLookupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateLookupResponse:
        """Test CreateLookupResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return CreateLookupResponse(
                request_id = '',
                status = 'COMPLETE'
            )
        else:
            return CreateLookupResponse(
        )

    def testCreateLookupResponse(self):
        """Test CreateLookupResponse"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, CreateLookupResponse)
        assert instance.request_id == ''
        assert instance.status == 'COMPLETE'

if __name__ == '__main__':
    unittest.main()
