# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.rbm_message_content_text import RbmMessageContentText
from bandwidth.models.multi_channel_action import MultiChannelAction
from bandwidth.models.rbm_action_base import RbmActionBase

class TestRbmMessageContentText(unittest.TestCase):
    """RbmMessageContentText unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RbmMessageContentText:
        """Test RbmMessageContentText
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return RbmMessageContentText(
                text = 'Hello world',
                suggestions = [
                    MultiChannelAction(
                        RbmActionBase(
                            type = 'REPLY',
                            text = 'Hello world',
                            post_back_data = '[B@32298473'
                        )
                    )
                ]
            )
        else:
            return RbmMessageContentText(
                text = 'Hello world',
        )

    def testRbmMessageContentText(self):
        """Test RbmMessageContentText"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, RbmMessageContentText)
        assert instance.text == 'Hello world'
        assert instance.suggestions is not None
        assert isinstance(instance.suggestions, list)
        assert isinstance(instance.suggestions[0], MultiChannelAction)

if __name__ == '__main__':
    unittest.main()
