# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.standalone_card_orientation_enum import StandaloneCardOrientationEnum

class TestStandaloneCardOrientationEnum(unittest.TestCase):
    """StandaloneCardOrientationEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStandaloneCardOrientationEnum(self):
        """Test StandaloneCardOrientationEnum"""
        assert StandaloneCardOrientationEnum('HORIZONTAL') == 'HORIZONTAL'
        assert StandaloneCardOrientationEnum('VERTICAL') == 'VERTICAL'

if __name__ == '__main__':
    unittest.main()
