# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.lookup_status_enum import LookupStatusEnum

class TestLookupStatusEnum(unittest.TestCase):
    """LookupStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLookupStatusEnum(self):
        """Test LookupStatusEnum"""
        in_progress = LookupStatusEnum('IN_PROGRESS')
        complete = LookupStatusEnum('COMPLETE')
        partial_complete = LookupStatusEnum('PARTIAL_COMPLETE')
        failed = LookupStatusEnum('FAILED')
        assert in_progress == 'IN_PROGRESS'
        assert complete == 'COMPLETE'
        assert partial_complete == 'PARTIAL_COMPLETE'
        assert failed == 'FAILED'

if __name__ == '__main__':
    unittest.main()
