# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.multi_channel_message_channel_enum import MultiChannelMessageChannelEnum

class TestMultiChannelMessageChannelEnum(unittest.TestCase):
    """MultiChannelMessageChannelEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiChannelMessageChannelEnum(self):
        """Test MultiChannelMessageChannelEnum"""
        rbm = MultiChannelMessageChannelEnum('RBM')
        sms = MultiChannelMessageChannelEnum('SMS')
        mms = MultiChannelMessageChannelEnum('MMS')
        assert rbm == 'RBM'
        assert sms == 'SMS'
        assert mms == 'MMS'

if __name__ == '__main__':
    unittest.main()
