# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.transcribe_recording import TranscribeRecording

class TestTranscribeRecording(unittest.TestCase):
    """TranscribeRecording unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranscribeRecording:
        """Test TranscribeRecording
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return TranscribeRecording(
                callback_url = 'https://myServer.example/bandwidth/webhooks/transcriptionAvailable',
                callback_method = 'POST',
                username = 'mySecretUsername',
                password = 'mySecretPassword1!',
                tag = 'exampleTag',
                callback_timeout = 5.5,
                detect_language = True
            )
        else:
            return TranscribeRecording(
        )

    def testTranscribeRecording(self):
        """Test TranscribeRecording"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, TranscribeRecording)
        assert instance.callback_url == 'https://myServer.example/bandwidth/webhooks/transcriptionAvailable'
        assert instance.callback_method == 'POST'
        assert instance.username == 'mySecretUsername'
        assert instance.password == 'mySecretPassword1!'
        assert instance.tag == 'exampleTag'
        assert instance.callback_timeout == 5.5
        assert instance.detect_language == True

if __name__ == '__main__':
    unittest.main()
