# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.business_registration_type_enum import BusinessRegistrationTypeEnum

class TestBusinessRegistrationTypeEnum(unittest.TestCase):
    """BusinessRegistrationTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBusinessRegistrationTypeEnum(self):
        """Test BusinessRegistrationTypeEnum"""
        ein = BusinessRegistrationTypeEnum('EIN')
        cbn = BusinessRegistrationTypeEnum('CBN')
        assert ein == 'EIN'
        assert cbn == 'CBN'



if __name__ == '__main__':
    unittest.main()
