# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from datetime import datetime

from bandwidth.models.device import Device
from bandwidth.models.device_status_enum import DeviceStatusEnum

class TestDevice(unittest.TestCase):
    """Device unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self) -> Device:
        """Test Device"""
        return Device(
            device_id='device-abc-123',
            device_name='My Test Device',
            status=DeviceStatusEnum.CONNECTED,
            creation_timestamp=datetime(2026, 1, 15, 10, 0, 0)
        )

    def testDevice(self):
        """Test Device"""
        instance = self.make_instance()
        assert instance is not None
        assert isinstance(instance, Device)
        assert instance.device_id == 'device-abc-123'
        assert instance.device_name == 'My Test Device'
        assert instance.status == DeviceStatusEnum.CONNECTED
        assert instance.creation_timestamp == datetime(2026, 1, 15, 10, 0, 0)

if __name__ == '__main__':
    unittest.main()
