# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bandwidth
from bandwidth.models.priority_enum import PriorityEnum  # noqa: E501
from bandwidth.rest import ApiException

class TestPriorityEnum(unittest.TestCase):
    """PriorityEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriorityEnum(self):
        """Test PriorityEnum"""
        # inst = PriorityEnum()

if __name__ == '__main__':
    unittest.main()
