# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.rbm_action_base import RbmActionBase

class TestRbmActionBase(unittest.TestCase):
    """RbmActionBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RbmActionBase:
        """Test RbmActionBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return RbmActionBase(
                type = 'REPLY',
                text = 'Hello world',
                post_back_data = '[B@32298473'
            )
        else:
            return RbmActionBase(
                type = 'REPLY',
                text = 'Hello world',
                post_back_data = '[B@32298473',
        )

    def testRbmActionBase(self):
        """Test RbmActionBase"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, RbmActionBase)
        assert instance.type == 'REPLY'
        assert instance.text == 'Hello world'
        assert instance.post_back_data == '[B@32298473'

if __name__ == '__main__':
    unittest.main()
