# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.redirect_method_enum import RedirectMethodEnum

class TestRedirectMethodEnum(unittest.TestCase):
    """RedirectMethodEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedirectMethodEnum(self):
        """Test RedirectMethodEnum"""
        get = RedirectMethodEnum('GET')
        post = RedirectMethodEnum('POST')
        assert get == 'GET'
        assert post == 'POST'

if __name__ == '__main__':
    unittest.main()
