# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.media import Media

class TestMedia(unittest.TestCase):
    """Media unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Media:
        """Test Media
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return Media(
                content = '',
                content_length = 56,
                media_name = ''
            )
        else:
            return Media(
        )

    def testMedia(self):
        """Test Media"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, Media)
        assert instance.content == ''
        assert instance.content_length == 56
        assert instance.media_name == ''

if __name__ == '__main__':
    unittest.main()
