# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.error_source import ErrorSource

class TestErrorSource(unittest.TestCase):
    """ErrorSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorSource:
        """Test ErrorSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return ErrorSource(
                parameter = 'parameter',
                var_field = 'var_field',
                header = 'header',
                reference = 'reference'
            )
        else:
            return ErrorSource(
        )

    def testErrorSource(self):
        """Test ErrorSource"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, ErrorSource)
        assert instance.parameter == 'parameter'
        assert instance.var_field == 'var_field'
        assert instance.header == 'header'
        assert instance.reference == 'reference'

if __name__ == '__main__':
    unittest.main()
