# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.error import Error
from bandwidth.models.telephone_number import TelephoneNumber

class TestError(unittest.TestCase):
    """Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Error:
        """Test Error
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return Error(
                code = 56,
                description = '',
                telephone_numbers = [
                    TelephoneNumber(
                        telephone_number = '', )
                    ]
            )
        else:
            return Error(
        )

    def testError(self):
        """Test Error"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, Error)
        assert instance.code == 56
        assert instance.description == ''
        assert isinstance(instance.telephone_numbers, list)
        assert len(instance.telephone_numbers) == 1
        assert isinstance(instance.telephone_numbers[0], TelephoneNumber)
        assert instance.telephone_numbers[0].telephone_number == ''

if __name__ == '__main__':
    unittest.main()
