# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from datetime import date
from uuid import UUID

from bandwidth.models.create_sync_lookup_response import CreateSyncLookupResponse
from bandwidth.models.create_sync_lookup_response_data import CreateSyncLookupResponseData
from bandwidth.models.lookup_result import LookupResult
from bandwidth.models.lookup_error_schema import LookupErrorSchema
from bandwidth.models.lookup_error_schema_meta import LookupErrorSchemaMeta

class TestCreateSyncLookupResponse(unittest.TestCase):
    """CreateSyncLookupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSyncLookupResponse:
        """Test CreateSyncLookupResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return CreateSyncLookupResponse(
                links = [],
                data = CreateSyncLookupResponseData(
                    request_id = UUID('004223a0-8b17-41b1-bf81-20732adf5590'), 
                    status = 'COMPLETE', 
                    results = [
                        LookupResult(
                            phone_number = '+10072904498', 
                            line_type = 'MOBILE', 
                            messaging_provider = 'Verizon Wireless', 
                            voice_provider = 'Verizon Wireless', 
                            country_code_a3 = 'USA', 
                            deactivation_reporter = '', 
                            deactivation_date = '2025-06-20 18:35', 
                            deactivation_event = 'DEACTIVATED', 
                            latest_message_delivery_status = 'ACTIVE', 
                            initial_message_delivery_status_date = '2025-06-20', 
                            latest_message_delivery_status_date = '2025-06-20', )
                        ], ),
                errors = [
                    LookupErrorSchema(
                        code = 'NO-MATCH', 
                        description = 'Example error description', 
                        type = 'NumberInventory', 
                        meta = LookupErrorSchemaMeta(
                            phone_numbers = ["+13992077164","+19196104424"], 
                            message = 'Invalid TNs', 
                            code = 1001, ), )
                    ]
            )
        else:
            return CreateSyncLookupResponse(
        )


    def testCreateSyncLookupResponse(self):
        """Test CreateSyncLookupResponse"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, CreateSyncLookupResponse)
        assert instance.links is not None
        assert isinstance(instance.data, CreateSyncLookupResponseData)
        assert instance.data.request_id == UUID('004223a0-8b17-41b1-bf81-20732adf5590')
        assert instance.data.status == 'COMPLETE'
        assert instance.data.results is not None
        assert isinstance(instance.data.results, list)
        assert isinstance(instance.data.results[0], LookupResult)
        assert instance.data.results[0].phone_number == '+10072904498'
        assert instance.data.results[0].line_type == 'MOBILE'
        assert instance.data.results[0].messaging_provider == 'Verizon Wireless'
        assert instance.data.results[0].voice_provider == 'Verizon Wireless'
        assert instance.data.results[0].country_code_a3 == 'USA'
        assert instance.data.results[0].deactivation_reporter == ''
        assert instance.data.results[0].deactivation_date == '2025-06-20 18:35'
        assert instance.data.results[0].deactivation_event == 'DEACTIVATED'
        assert instance.data.results[0].latest_message_delivery_status == 'ACTIVE'
        assert isinstance(instance.data.results[0].initial_message_delivery_status_date, date)
        assert isinstance(instance.data.results[0].latest_message_delivery_status_date, date)

if __name__ == '__main__':
    unittest.main()
