# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.page_info import PageInfo

class TestPageInfo(unittest.TestCase):
    """PageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageInfo:
        """Test PageInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return PageInfo(
                prev_page = 'https://messaging.bandwidth.com/api/v2/users/accountId/messages?messageStatus=DLR_EXPIRED&nextPage=DLAPE902',
                next_page = 'https://messaging.bandwidth.com/api/v2/users/accountId/messages?messageStatus=DLR_EXPIRED&prevPage=GL83PD3C',
                prev_page_token = 'DLAPE902',
                next_page_token = 'GL83PD3C'
            )
        else:
            return PageInfo(
        )

    def testPageInfo(self):
        """Test PageInfo"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, PageInfo)
        assert instance.prev_page == 'https://messaging.bandwidth.com/api/v2/users/accountId/messages?messageStatus=DLR_EXPIRED&nextPage=DLAPE902'
        assert instance.next_page == 'https://messaging.bandwidth.com/api/v2/users/accountId/messages?messageStatus=DLR_EXPIRED&prevPage=GL83PD3C'
        assert instance.prev_page_token == 'DLAPE902'
        assert instance.next_page_token == 'GL83PD3C'

if __name__ == '__main__':
    unittest.main()
