# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from datetime import datetime

from bandwidth.models.message_sending_callback import MessageSendingCallback
from bandwidth.models.message_sending_callback_message import MessageSendingCallbackMessage

class TestMessageSendingCallback(unittest.TestCase):
    """MessageSendingCallback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageSendingCallback:
        """Test MessageSendingCallback
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return MessageSendingCallback(
                time = '2016-09-14T18:20:16Z',
                type = 'message-sending',
                to = '+15552223333',
                description = 'Message is sending to carrier',
                message = MessageSendingCallbackMessage(
                    id = '1661365814859loidf7mcwd4qacn7', 
                    owner = '+15553332222', 
                    application_id = '93de2206-9669-4e07-948d-329f4b722ee2', 
                    time = '2016-09-14T18:20:16Z', 
                    segment_count = 1, 
                    direction = 'in', 
                    to = ["+15552223333"], 
                    var_from = '+15553332222', 
                    text = 'Hello world', 
                    tag = 'custom string', 
                    media = ["https://dev.bandwidth.com/images/bandwidth-logo.png","https://dev.bandwidth.com/images/github_logo.png"], 
                    priority = 'default', )
            )
        else:
            return MessageSendingCallback(
                time = '2016-09-14T18:20:16Z',
                type = 'message-sending',
                to = '+15552223333',
                description = 'Message is sending to carrier',
                message = MessageSendingCallbackMessage(
                    id = '1661365814859loidf7mcwd4qacn7', 
                    owner = '+15553332222', 
                    application_id = '93de2206-9669-4e07-948d-329f4b722ee2', 
                    time = '2016-09-14T18:20:16Z', 
                    segment_count = 1, 
                    direction = 'in', 
                    to = ["+15552223333"], 
                    var_from = '+15553332222', 
                    text = 'Hello world', 
                    tag = 'custom string', 
                    media = ["https://dev.bandwidth.com/images/bandwidth-logo.png","https://dev.bandwidth.com/images/github_logo.png"], 
                    priority = 'default', ),
        )

    def testMessageSendingCallback(self):
        """Test MessageSendingCallback"""
        instance = self.make_instance(True)
        assert instance is not None
        assert isinstance(instance, MessageSendingCallback)
        assert isinstance(instance.time, datetime)
        assert instance.type == 'message-sending'
        assert instance.to == '+15552223333'
        assert instance.description == 'Message is sending to carrier'
        assert isinstance(instance.message, MessageSendingCallbackMessage)
        assert instance.message.id == '1661365814859loidf7mcwd4qacn7'
        assert instance.message.owner == '+15553332222'
        assert instance.message.application_id == '93de2206-9669-4e07-948d-329f4b722ee2'
        assert isinstance(instance.message.time, datetime)
        assert instance.message.segment_count == 1
        assert instance.message.direction == 'in'
        assert instance.message.to == ["+15552223333"]
        assert instance.message.var_from == '+15553332222'
        assert instance.message.text == 'Hello world'
        assert instance.message.tag == 'custom string'
        assert instance.message.media == ["https://dev.bandwidth.com/images/bandwidth-logo.png","https://dev.bandwidth.com/images/github_logo.png"]
        assert instance.message.priority == 'default'

if __name__ == '__main__':
    unittest.main()
