# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bandwidth.models.endpoint_type_enum import EndpointTypeEnum

class TestEndpointTypeEnum(unittest.TestCase):
    """EndpointTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointTypeEnum(self):
        """Test EndpointTypeEnum"""
        # Test that the enum has the expected value
        assert EndpointTypeEnum.WEBRTC == 'WEBRTC'

        # Test enum instantiation
        instance = EndpointTypeEnum.WEBRTC
        assert instance is not None
        assert isinstance(instance, EndpointTypeEnum)

        # Test from_json
        json_str = '"WEBRTC"'
        instance_from_json = EndpointTypeEnum.from_json(json_str)
        assert instance_from_json == EndpointTypeEnum.WEBRTC

if __name__ == '__main__':
    unittest.main()
