# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class TwoFactorVerifyCodeResponse(object):

    """Implementation of the 'TwoFactorVerifyCodeResponse' model.

    TODO: type model description here.

    Attributes:
        valid (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "valid": 'valid'
    }

    def __init__(self,
                 valid=None):
        """Constructor for the TwoFactorVerifyCodeResponse class"""

        # Initialize members of the class
        self.valid = valid

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        valid = dictionary.get('valid')

        # Return an object of this model
        return cls(valid)
