# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ConferenceEventMethodEnum(object):

    """Implementation of the 'ConferenceEventMethod' enum.

    TODO: type enum description here.

    Attributes:
        GET: TODO: type description here.
        HEAD: TODO: type description here.
        POST: TODO: type description here.
        PUT: TODO: type description here.
        PATCH: TODO: type description here.
        DELETE: TODO: type description here.
        OPTIONS: TODO: type description here.
        TRACE: TODO: type description here.

    """

    GET = 'GET'

    HEAD = 'HEAD'

    POST = 'POST'

    PUT = 'PUT'

    PATCH = 'PATCH'

    DELETE = 'DELETE'

    OPTIONS = 'OPTIONS'

    TRACE = 'TRACE'
