# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FallbackMethodEnum(object):

    """Implementation of the 'FallbackMethod' enum.

    TODO: type enum description here.

    Attributes:
        POST: TODO: type description here.
        GET: TODO: type description here.

    """

    POST = 'POST'

    GET = 'GET'
