# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class State1Enum(object):

    """Implementation of the 'State1' enum.

    TODO: type enum description here.

    Attributes:
        NOT_RECORDING: TODO: type description here.
        PAUSED: TODO: type description here.
        RECORDING: TODO: type description here.

    """

    NOT_RECORDING = 'NOT_RECORDING'

    PAUSED = 'PAUSED'

    RECORDING = 'RECORDING'
