# -*- coding: utf-8 -*-

"""
bandwidth

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PriorityEnum(object):

    """Implementation of the 'Priority' enum.

    The message's priority, currently for toll-free or short code SMS only.
    Messages with a priority value of `"high"` are given preference over your
    other traffic.

    Attributes:
        DEFAULT: TODO: type description here.
        HIGH: TODO: type description here.

    """

    DEFAULT = 'default'

    HIGH = 'high'
