# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bandwidth
from bandwidth.models.transcription_metadata import TranscriptionMetadata  # noqa: E501
from bandwidth.rest import ApiException

class TestTranscriptionMetadata(unittest.TestCase):
    """TranscriptionMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TranscriptionMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranscriptionMetadata`
        """
        model = bandwidth.models.transcription_metadata.TranscriptionMetadata()  # noqa: E501
        if include_optional :
            return TranscriptionMetadata(
                id = 't-387bd648-18f3-4823-9d16-746bca0003c9', 
                status = 'completed', 
                completed_time = '2022-06-13T18:46:29.715Z', 
                url = 'https://voice.bandwidth.com/api/v2/accounts/9900000/calls/c-15ac29a2-1331029c-2cb0-4a07-b215-b22865662d85/recordings/r-15ac29a2-1331029c-2cb0-4a07-b215-b22865662d85/transcription'
            )
        else :
            return TranscriptionMetadata(
        )
        """

    def testTranscriptionMetadata(self):
        """Test TranscriptionMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
