# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bandwidth
from bandwidth.models.messaging_code_response import MessagingCodeResponse  # noqa: E501
from bandwidth.rest import ApiException

class TestMessagingCodeResponse(unittest.TestCase):
    """MessagingCodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MessagingCodeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessagingCodeResponse`
        """
        model = bandwidth.models.messaging_code_response.MessagingCodeResponse()  # noqa: E501
        if include_optional :
            return MessagingCodeResponse(
                message_id = '9e0df4ca-b18d-40d7-a59f-82fcdf5ae8e6'
            )
        else :
            return MessagingCodeResponse(
        )
        """

    def testMessagingCodeResponse(self):
        """Test MessagingCodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
