# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bandwidth
from bandwidth.models.voice_code_response import VoiceCodeResponse  # noqa: E501
from bandwidth.rest import ApiException

class TestVoiceCodeResponse(unittest.TestCase):
    """VoiceCodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VoiceCodeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceCodeResponse`
        """
        model = bandwidth.models.voice_code_response.VoiceCodeResponse()  # noqa: E501
        if include_optional :
            return VoiceCodeResponse(
                call_id = 'c-15ac29a2-1331029c-2cb0-4a07-b215-b22865662d85'
            )
        else :
            return VoiceCodeResponse(
        )
        """

    def testVoiceCodeResponse(self):
        """Test VoiceCodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
