# coding: utf-8

"""
    Bandwidth

    Bandwidth's Communication APIs

    The version of the OpenAPI document: 1.0.0
    Contact: letstalk@bandwidth.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bandwidth
from bandwidth.models.callback_method_enum import CallbackMethodEnum  # noqa: E501
from bandwidth.rest import ApiException

class TestCallbackMethodEnum(unittest.TestCase):
    """CallbackMethodEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCallbackMethodEnum(self):
        """Test CallbackMethodEnum"""
        # inst = CallbackMethodEnum()

if __name__ == '__main__':
    unittest.main()
