# Ingest repository_dispatch events and trigger appropriate actions
name: Listener

on:
  repository_dispatch:
    types: [Build]

jobs:
  build:
    if: ${{ github.event.action == 'Build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get GH Access Token
        uses: Bandwidth/vault-provider-action@v1
        with:
          identity-source: repo
          durable-team-name: BAND SWI
          export-github-pat: true

      - uses: actions/checkout@v2

      - name: Build SDK and Open PR
        uses: Bandwidth/generate-sdk-action@v1.0.0
        with:
          branch-name: ${{ github.event.client_payload.branchName }}
          username: ${{ secrets.DX_GITHUB_USERNAME }}
          token: ${{ env.GITHUB_ACCESS_TOKEN }}
          openapi-generator-version: v5.4.0
          language: python
          config: ./openapi-config.yml
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_ACCESS_TOKEN }}

      - name: Open Pull Request
        run: |
          exists=$(hub pr list -h {{ inputs.branch-name }})
          if [ -z "$exists" ]
          then
            hub pull-request --base Bandwidth:main -m '${{ github.event.client_payload.branchName }}' -m 'Generate SDK with Upstream API Spec Changes. Opened By: @${{ github.event.client_payload.author }}'
          else
            echo "PR already exists for this branch"
          fi
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_ACCESS_TOKEN }}

      - name: Output PR Number
        id: output-pr-number
        run: echo "PR_NUMBER=$(hub pr list -h ${{ inputs.branch-name }} -f %I)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_ACCESS_TOKEN }}

      - uses: actions/github-script@v6
        with:
          github-token: ${{env.GITHUB_ACCESS_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.client_payload.prNumber }},
              owner: context.repo.owner,
              repo: 'api-specs',
              body: 'Python SDK built successfully\n\nSee the corresponding PR opened on the SDK repository (no action required):\nhttps://github.com/Bandwidth/api-docs/pull/${{ env.PR_NUMBER }}'
            })

      - name: Notify for Failure
        uses: actions/github-script@v6
        if: failure()
        with:
          github-token: ${{env.GITHUB_ACCESS_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.client_payload.prNumber }},
              owner: context.repo.owner,
              repo: 'api-specs',
              body: 'Python SDK failed to build successfully\n\nSee the Python SDK repository [action logs](https://github.com/Bandwidth/python-sdk/actions) for more information.'
            })
