name: Smoke Tests

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: false
        default: WARNING
        type: choice
        options:
          - WARNING
          - DEBUG
  pull_request:
    branches:
      - main
    paths:
      - 'test/smoke/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
  BW_USERNAME: ${{ secrets.BW_USERNAME }}
  BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
  BW_USERNAME_FORBIDDEN: ${{ secrets.BW_USERNAME_FORBIDDEN }}
  BW_PASSWORD_FORBIDDEN: ${{ secrets.BW_PASSWORD_FORBIDDEN }}
  BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
  BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
  BW_NUMBER: ${{ secrets.BW_NUMBER }}
  USER_NUMBER: ${{ secrets.USER_NUMBER }}
  VZW_NUMBER: ${{ secrets.VZW_NUMBER }}
  ATT_NUMBER: ${{ secrets.ATT_NUMBER }}
  T_MOBILE_NUMBER: ${{ secrets.T_MOBILE_NUMBER }}
  BASE_CALLBACK_URL: ${{ secrets.BASE_CALLBACK_URL }}
  MANTECA_ACTIVE_NUMBER: ${{ secrets.MANTECA_ACTIVE_NUMBER }}
  MANTECA_IDLE_NUMBER: ${{ secrets.MANTECA_IDLE_NUMBER }}
  MANTECA_BASE_URL: ${{ secrets.MANTECA_BASE_URL }}
  MANTECA_APPLICATION_ID: ${{ secrets.MANTECA_APPLICATION_ID }}

jobs:
  test:
    name: Smoke Test
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.12'
      OPERATING_SYSTEM: ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Packages
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Test at Debug Level
        if: ${{ inputs.logLevel == 'DEBUG' }}
        run: |
          echo "Log level: DEBUG"
          pytest -v --log-cli-level=DEBUG

      - name: Test at Warning Level
        if: ${{( inputs.logLevel == null) || ( inputs.logLevel  == 'WARNING') }}
        run: |
          echo "Log level: WARNING"
          pytest -v --log-cli-level=WARNING ./test/smoke

  notify_for_failures:
    name: Notify for Failures
    needs: [test]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack of Failures
        uses: Bandwidth/build-notify-slack-action@v2.0.0
        with:
          job-status: failure
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
